[build]
builder = "nixpacks"
buildCommand = "pip install ."

[deploy]
startCommand = "python -m src.daad.main"

[services.rabbitmq]
image = "rabbitmq:3-management"
healthcheck.path = "/health"
healthcheck.interval = "15s"
healthcheck.timeout = "5s"
# cron jobs
# [tasks]
# [tasks.daily_task]
#   schedule = "0 3 * * *" # Runs daily at 3 AM
#   command = "python -m src.daad.main"
