[build]
# builder = "nixpacks"
builder = "INVALID_BUILDER_NAME"
buildCommand = "pip install ."

[deploy]
startCommand = "python -m src.daad.main"

[services.rabbitmq]
plugin = "rabbitmq"
name = "rabbitmq"

# cron jobs
# [tasks]
# [tasks.daily_task]
#   schedule = "0 3 * * *" # Runs daily at 3 AM
#   command = "python -m src.daad.main"
